spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 20000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update  # Keep as 'update', not 'validate'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${PORT:8080}
logging:
  level:
    com.dashboard.api: INFO
    org.springframework.web: WARN